[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = ["ALL"]
ignore = [
    "D203",    # Incompatible with D211.
    "D213",    # Incompatible with D212.
    "PLE1205", # Loguru uses template strings, so this error is not applicable.
]
